### ISSUE TITLE
Intl version

### ISSUE THREAD

**Issue by FMorschel** [gokberkbar/locale_plus#12]
When using `flutter_localizations` this way:

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
```

And adding `locale_plus: ^1.5.0` I get:

```
Because locale_plus 1.5.0 depends on intl ^0.18.0 and no versions of locale_plus match >1.5.0 <2.0.0, locale_plus ^1.5.0 requires intl ^0.18.0.
[...]
flutter_localizations from sdk depends on intl 0.19.0, custom_fields from path is incompatible with flutter_localizations from sdk.
```

My question is, would it be breaking if you replaced `intl` version for `any` or something like that?
