### ISSUE TITLE
Flutter 3.32.0 requires intl: ^0.20.2

### ISSUE THREAD

**Issue by Shakle** [gokberkbar/locale_plus#16]
Does not work with Flutter 3.32.0

**Comment by LucaCras** [comment]
Running into this issue as well

**Comment by BentEngbers** [comment]
I have added a PR (#17) that makes the relevant changes. You can use my fork as a workaround until that PR is merged, by pulling `locale_plus` from my fork.
```yaml
  locale_plus:
    git:
      url: https://github.com/BentEngbers/locale_plus
      ref: f7566e720bb3ee7fcb22041c24099db436152cdf
```
